server:
  port: 9999
#设置实体所在的包，然后在mapper.xml里面不用写实体的全名，直接写实体的以小写字母开头的简单类名即可,例如：com.tracker.entity.User,可以直接写user
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.example.xnlogin.controller
  configuration:
    mapUnderscoreToCamelCase: true

spring:
  datasource:
    url: jdbc:oracle:thin:@192.168.21.244:1521/orcl
    username: platform
    password: platform
    driverClassName: oracle.jdbc.driver.OracleDriver
